name: Triage PR

on:
 pull_request:
   types: [opened, edited, synchronize]

jobs:
 triage:
   uses: TicketsBot-cloud/template/.github/workflows/auto-label.yaml@main
   permissions:
     contents: read
     pull-requests: write
